django_todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('todolist.urls', namespace='todolist')),
    path('admin/', admin.site.urls),
]

todolist/urls.py
from django.urls import path, include



from . import views

app_name = 'todolist'

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', views.TodoitemsToday.as_view(), name='index'),
    path('refresh/', views.refresh_task, name='refresh'),
    path('projects/', views.ProjectListView.as_view(), name='projects'),
    path('projects/add', views.ProjectCreateView.as_view(), name='project_add'),
    path('projects/<pk>', views.ProjectDetailView.as_view(), name='project_details'),
    path('projects/edit/<pk>', views.ProjectUpdateView.as_view(), name='project_edit'),
    path('projects/delete/<pk>', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('todo/', views.TodoitemsListView.as_view(), name='todoitems'),
    path('todo/add', views.TodoitemCreateView.as_view(), name='todoitem_add'),
    path('todo/edit/<pk>', views.TodoitemUpdateView.as_view(), name='todoitem_edit'),
    path('todo/edit/time/<pk>', views.TodoitemUpdateTimeView.as_view(), name='todoitem_time_edit'),
    path('todo/delete/<pk>', views.TodoitemDeleteView.as_view(), name='todoitem_delete'),
    path('todo/details/<pk>', views.TodoitemDetailView.as_view(), name='todoitem_detail'),
    path('todo/done/<pk>/next=<path:next>', views.TodoitemDoneView.as_view(), name='todoitem_done'),
    path('todo/by_project/<int:id>', views.TodoitemsListView.as_view(), name='show_todo_by_proj'),
]

todolist/models.py
import dateutil.relativedelta
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone

class Label(models.Model):
    label_id = models.AutoField(primary_key=True)
    text = models.CharField(max_length=100, unique=True)

    def __repr__(self):
        return f"Label({self.label_id}) text:'{self.text}'"

    def __str__(self):
        return self.__repr__()

class Project(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('todolist:project_details', kwargs={'pk':self.id})

    def __str__(self):
        return f"{self.name}"

    def __repr__(self):
        return f"{self.id}"

class TodoitemPeriodType():
    NONE = 0
    EVERY_DAY = 1
    EVERY_WEEK = 2
    EVERY_MONTH = 3
    EVERY_YEAR = 4

    CHOICES = [
        (NONE, 'Brak'),
        (EVERY_DAY, 'Co dzień'),
        (EVERY_WEEK, 'Co tydzień'),
        (EVERY_MONTH, 'Co miesiąc'),
        (EVERY_YEAR, 'Co rok'),
    ]


class TodoItem(models.Model):
    text = models.CharField(unique=False, max_length=1024)
    label_id = models.ForeignKey(Label, on_delete=models.CASCADE, null=True)
    due_date = models.DateField(null=True)
    due_time = models.TimeField(null=True, blank=True)
    period_value = models.PositiveSmallIntegerField(null=False, default=1, validators=[MinValueValidator(1),])
    period_type = models.PositiveSmallIntegerField(null=False, default=0, choices=TodoitemPeriodType.CHOICES)

    PRIORITY_CHOICES = [
        (0, 'Najważeniejszy'),
        (1, 'Prawie najważniejszy'),
        (2, 'Wysoki'),
        (3, 'Normalny'),
        (4, 'Niski'),
    ]

    priority = models.PositiveSmallIntegerField(choices=PRIORITY_CHOICES, default=3)
    project = models.ForeignKey(Project, related_name='project_todoitems', on_delete=models.CASCADE, null=True)
    done_date = models.DateTimeField(null=True)


    def done(self):
        if self.period_type == TodoitemPeriodType.NONE:
            self.done_date = timezone.now()
            self.save()
        else:
            switcher = {
                TodoitemPeriodType.EVERY_DAY : 'days',
                TodoitemPeriodType.EVERY_WEEK: 'weeks',
                TodoitemPeriodType.EVERY_MONTH: 'months',
                TodoitemPeriodType.EVERY_YEAR: 'years',
            }
            kwargs = { switcher.get(self.period_type): self.period_value}
            self.due_date += dateutil.relativedelta.relativedelta(**kwargs)
            self.save()

    def get_absolute_url(self):
        return reverse('todolist:todoitem_detail', kwargs={'pk':self.id})

    def __repr__(self):
        return f"TodoItem({self.id}) '{self.text}'"

    def __str__(self):
        return self.__repr__()



todolist/forms.py
from django import forms
from django.forms import DateInput, TimeInput

from . import models

class TodoitemForm(forms.ModelForm):
    class Meta:
        model = models.TodoItem
        fields = ('text', 'priority', 'project')
        widgets = {
            'due_date': DateInput,
            'due_time': TimeInput,
        }

class TodoitemTimeForm(forms.ModelForm):
    class Meta:
        model = models.TodoItem
        fields = ('period_type', 'period_value', 'due_date', 'due_time')
        widgets = {
            'due_date': DateInput,
            'due_time' : TimeInput,
        }

todolist/views.py
from django.forms import ModelForm, SelectDateWidget, SplitDateTimeWidget, DateTimeInput
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.http import is_safe_url
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from todolist.forms import TodoitemForm, TodoitemTimeForm
from . import models


# Create your views here.

class ProjectListView(ListView):
    template_name = 'todolist/projects.html'
    context_object_name = 'projects'
    model = models.Project

    def get_queryset(self):
        return models.Project.objects.all()


class ProjectDetailView(DetailView):
    context_object_name = 'project_detail'
    model = models.Project
    template_name = 'todolist/project_details.html'


class ProjectCreateView(CreateView):
    model = models.Project
    fields = ('name', 'description',)


class ProjectUpdateView(UpdateView):
    model = models.Project
    fields = ('name', 'description',)


class ProjectDeleteView(DeleteView):
    model = models.Project
    success_url = reverse_lazy('todolist:projects')


class TodoitemCreateView(CreateView):
    model = models.TodoItem
    form_class = TodoitemForm


class TodoitemUpdateView(UpdateView):
    model = models.TodoItem
    form_class = TodoitemForm


class TodoitemUpdateTimeView(UpdateView):
    model = models.TodoItem
    form_class = TodoitemTimeForm


class TodoitemDeleteView(DeleteView):
    model = models.TodoItem
    success_url = reverse_lazy('todolist:todoitems')


class TodoitemsListView(ListView):
    template_name = 'todolist/todoitem.html'
    context_object_name = 'todo_list'
    model = models.TodoItem

    def get_queryset(self):
        if 'id' in self.kwargs:
            project = get_object_or_404(models.Project, id=self.kwargs['id'])
            return models.TodoItem.objects.filter(done_date=None).filter(project=project)
        else:
            return models.TodoItem.objects.filter(done_date=None)


class TodoitemsToday(TodoitemsListView):
    def get_queryset(self):
        queryset = super().get_queryset()
        tomorrow = timezone.datetime.today() + timezone.timedelta(days=1)
        return queryset.filter(due_date__lt=timezone.make_aware(tomorrow))


class TodoitemDetailView(DetailView):
    context_object_name = 'todoitem'
    model = models.TodoItem
    template_name = 'todolist/todoitem_detail.html'


def refresh_task(request):
    tomorrow = timezone.datetime.today() + timezone.timedelta(days=1)
    overdue_cyclic_queryset = models.TodoItem.objects.filter(due_date__lt=timezone.make_aware(tomorrow)).filter(period_type__gt=0)
    for task in overdue_cyclic_queryset:
        due_date = task.due_date
        task.done()
        #new object
        task.pk = None
        task.due_date = due_date
        task.period_type = models.TodoitemPeriodType.NONE
        task.save()

    return redirect('todolist:index')

class TodoitemDoneView(View):
    def get(self, request, *args, **kwargs):
        obj = get_object_or_404(models.TodoItem, pk=kwargs['pk'])
        obj.done()
        redirect_path = kwargs['next']
        if is_safe_url(redirect_path, allowed_hosts=request.get_host()):
            return HttpResponseRedirect(redirect_path)
        return redirect('todolist:index')

todolist/templates/todolist/base.html
<!DOCTYPE html>
<html lang="pl" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% block title %}
    <title>BASE</title>
    {% endblock %}
</head>
<body>

<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'todolist:index' %}">MAIN</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'todolist:projects' %}">Projects</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'todolist:todoitems' %}">Todoitems</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            </ul>
        </div>
    </nav>
</div>
{% block sub_menu %}
{% endblock %}

<div class="container">
    {% block body_block %}
        <p>Welcome!</p>
    {% endblock %}
</div>
</body>
</html>

todolist/templates/todolist/form_add_project.html
{% extends 'todolist/projects.html' %}

{% block title %}
    <title>Add project</title>
{% endblock %}

{% block body_block %}
    <div class="container">
        <form method="POST" >
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" , class="btn btn-primary" , value="Submit">
        </form>

    </div>

{% endblock %}

todolist/templates/todolist/form_add_todoitem.html
{% extends 'todolist/projects.html' %}

{% block title %}
    <title>Add todo item</title>
{% endblock %}

{% block body_block %}
    <div class="container">
        <form method="POST" >
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" , class="btn btn-primary" , value="Submit">
        </form>

    </div>

{% endblock %}

todolist/templates/todolist/project_confirm_delete.html
{% extends 'todolist/base.html' %}

{% block title %}
    <title>Confirm delete project</title>
{% endblock %}

{% block body_block %}
    <div class="jumbotron">

    <h1>Please confirm deletion</h1>
    <p> of <br />"{{ project.name }}"</p>
    <form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'todolist:project_details' pk=project.id %} ">Cancel</a>

</form>

    </div>
{% endblock %}

todolist/templates/todolist/project_details.html
{% extends 'todolist/base.html' %}

{% block title %}
    <title>Project detail</title>
{% endblock %}


{% block sub_menu %}
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="{% url 'todolist:todoitem_add' %}">Add todo</a></li>
                </ul>
            </div>
        </nav>
    </div>
{% endblock %}

{% block body_block %}
    <div class="jumbotron">

    <h1>Welcome to project detail view</h1>
    <p>ID: {{ project_detail.id }}</p>
    <p>Name: {{ project_detail.name }}</p>
    <p>Description: {{ project_detail.description }}</p>
    </div>
{% endblock %}

todolist/templates/todolist/project_form.html
{% extends 'todolist/base.html' %}

{% block title %}
    {% if not form.instance.pk %}
    <title>Create project</title>
    {% else %}
    <title>Update project</title>
    {% endif %}
{% endblock %}

{% block body_block %}
    <div class="container">
        <form method="POST" >
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" , class="btn btn-primary" , value="Submit">
        </form>

    </div>

{% endblock %}

todolist/templates/todolist/projects.html
{% extends 'todolist/base.html' %}

{% block title %}
    <title>Projects</title>
{% endblock %}


{% block sub_menu %}
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="{% url 'todolist:project_add' %}">Add project</a></li>
                </ul>
            </div>
        </nav>
    </div>
{% endblock %}

{% block body_block %}
    <div class="jumbotron">
        {% if projects %}
            <ul>
                {% for project in projects %}
                    <li> <a href="{% url 'todolist:show_todo_by_proj' project.id %}">{{ project.name }}</a> </li>
                    <p>{{ project.description }}</p>
                    <a href="{% url 'todolist:project_edit' project.id %}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'todolist:project_delete' project.id %}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'todolist:project_details' project.id %}" class="btn btn-info">Details</a>
                    <br/>
                {% endfor %}
            </ul>
        {% else %}
            <p>No projects available</p>
        {% endif %}
    </div>
{% endblock %}

todolist/templates/todolist/todo.html
{% extends 'todolist/base.html' %}

{% block title %}
    <title>Todo</title>
{% endblock %}


{% block sub_menu %}
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="{% url 'todolist:todoitem_add' %}">Add todo</a></li>
                </ul>
            </div>
        </nav>
    </div>
{% endblock %}

{% block body_block %}
    <div class="jumbotron">
        {% if todo_list %}
            <ul>
                {% for todo in todo_list %}
                    <li><a href="{% url 'todolist:todoitem_detail' todo.id %}">{{ todo.text }}</a> </li>
                    <p>  {{ todo.due_date }} </p>
                    <form method="POST" action="{% url 'todolist:todoitem_delete' todo.id %}">
                        {{ form.as_p }}
                        {% csrf_token %}
                        <input type="submit" , class="btn btn-primary" , value="Delete">
                    </form>

                    <br/>
                {% endfor %}
            </ul>
        {% else %}
            <p>No todo items available</p>
        {% endif %}
    </div>
{% endblock %}

todolist/templates/todolist/todoitem.html
{% extends 'todolist/base.html' %}

{% block title %}
    <title>Todo</title>
{% endblock %}


{% block sub_menu %}
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="{% url 'todolist:todoitem_add' %}">Add todo</a></li>
                </ul>
            </div>
        </nav>
    </div>
{% endblock %}

{% block body_block %}
    <div class="jumbotron">
        {% if todo_list %}
            <ul>
                {% for todoitem in todo_list %}
                    <li>
                    <a href="{% url 'todolist:todoitem_done' todoitem.id request.path %}"><button class="btn">done</button></a>
                    <a href="{% url 'todolist:todoitem_detail' todoitem.id %}">{{ todoitem.text }}</a>
                    {% if todoitem.due_date %} {{ todoitem.due_date }} {% endif %}
                    {% if todoitem.period_type > 0 %} (periodic) {% endif %}
                    {% if todoitem.project %} - {{ todoitem.project.name }} {% endif %}
                    </li>

                    <br/>
                {% endfor %}
            </ul>
        {% else %}
            <p>No todo items available</p>
        {% endif %}
    </div>
{% endblock %}

todolist/templates/todolist/todoitem_confirm_delete.html
{% extends 'todolist/base.html' %}

{% block title %}
    <title>Confirm delete todoitem</title>
{% endblock %}

{% block body_block %}
    <div class="jumbotron">

    <h1>Please confirm deletion</h1>
    <p> of <br />"{{ todoitem.text }}"</p>
    <form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'todolist:todoitem_detail' pk=todoitem.id %} ">Cancel</a>

</form>

    </div>
{% endblock %}

todolist/templates/todolist/todoitem_detail.html
{% extends 'todolist/base.html' %}

{% block title %}
    <title>Todoitem detail</title>
{% endblock %}


{% block sub_menu %}
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="{% url 'todolist:todoitem_add' %}">Add todo</a></li>
                </ul>
            </div>
        </nav>
    </div>
{% endblock %}

{% block body_block %}
    <div class="jumbotron">

    <h1>Welcome to todoitem detail view</h1>
    <p>ID: {{ todoitem.id }}</p>
    <p>TEXT: {{ todoitem.text }}</p>
    <p>PRIORITY: {{ todoitem.get_priority_display }}</p>
    <p>DUE_DATE: {{ todoitem.due_date }}</p>
        {% if todoitem.due_time %}
            <p>Time: {{ todoitem.due_time }}</p>
        {% endif %}
        {% if todoitem.period_type %}
            <p>Cyclic: {{ todoitem.get_period_type_display }}, period: {{ todoitem.period_value }}</p>
        {% endif %}

    <p>PROJECT: {{ todoitem.project }}</p>
    <a href="{% url 'todolist:todoitem_delete' todoitem.id %}" class="btn btn-danger">Delete</a>
    <a href="{% url 'todolist:todoitem_edit' todoitem.id %}" class="btn btn-warning">Edit</a>
    <a href="{% url 'todolist:todoitem_time_edit' todoitem.id %}" class="btn btn-warning">Edit time</a>

    </div>
{% endblock %}

todolist/templates/todolist/todoitem_form.html
{% extends 'todolist/base.html' %}

{% block title %}
    {% if not form.instance.pk %}
    <title>Create todoitem</title>
    {% else %}
    <title>Update todoitem</title>
    {% endif %}
{% endblock %}

{% block body_block %}
    <div class="container">
        <form method="POST" >
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" , class="btn btn-primary" , value="Submit">
        </form>

    </div>

{% endblock %}